export enum QueryKeys {
  EDIT_IMAGE_STATE = "EDIT IMAGE STATE",
  EIDT_IMAGE_UPLOADING = "EDIT IMAGE UPLOADING",
  //WORKSPACE
  CURRENT_WORKSPACE = "CURRENT_WORKSPACE",
  WORKSPACE_LIST = "WORKSPACE_LIST",
}
